declare const TEXTURE_SINGLE_WHITE_PIXEL: number;
declare const TEXTURE_WHITE_CIRCLE: number;
declare const TEXTURE_D_PAD: number;
declare const TEXTURE_LEFT_WALL: number;
declare const TEXTURE_CENTER_WALL: number;
declare const TEXTURE_RIGHT_WALL: number;
declare const TEXTURE_FLOOR: number;
declare const TEXTURE_PLAYER: number;
declare const TEXTURE_TORCH: number;