const TEXTURE_TYPES = {
  TEXTURE_TYPE_FONT: 0,
  TEXTURE_TYPE_SPRITE: 1,
  TEXTURE_TYPE_SPRITE_STRIP: 2,
};

let texture_id = 0;
const TEXTURES = {
  TEXTURE_SINGLE_WHITE_PIXEL: texture_id++,

  TEXTURE_SWORD: texture_id++,
  TEXTURE_SHEILD: texture_id++,
  TEXTURE_FIRE: texture_id++,
  TEXTURE_ICE: texture_id++,
  TEXTURE_HOLY: texture_id++,
  TEXTURE_SHADOW: texture_id++,

  TEXTURE_WHITE_CIRCLE: texture_id++,
  TEXTURE_D_PAD: texture_id++,

  TEXTURE_ROBED_MAN_0: texture_id++,
  TEXTURE_BANDIT_0: texture_id++,
  TEXTURE_SKELETON_0: texture_id++,
  TEXTURE_ZOMBIE_0: texture_id++,
  TEXTURE_WALL_0: texture_id++,
  TEXTURE_WALL_1: texture_id++,
  TEXTURE_WALL_2: texture_id++,
  TEXTURE_FLOOR_0: texture_id++,
  TEXTURE_FLOOR_1: texture_id++,
  TEXTURE_FLOOR_2: texture_id++,
};

const FONTS = {
  TEXT_ALIGN_LEFT: 0,
  TEXT_ALIGN_CENTER: 1,
  TEXT_ALIGN_RIGHT: 2,

  FONT_NORMAL: 200,
  FONT_SMALL: 400,
};

let interp_id = 0;
const INTERPOLATION_IDS = {
  INTERP_SCENE_TRANSITION: interp_id++,
  INTERP_CAMERA_MOVEMENT: interp_id++,
  INTERP_PLAYER_MOVEMENT: interp_id++,
};

const GL = {
  GL_TEXTURE2D: 3553,
  GL_TEXTURE0: 33984,
  GL_TEXTURE1: 33985,
  GL_BYTE: 5120,
  GL_UNSIGNED_BYTE: 5121,
  GL_SHORT: 5122,
  GL_UNSIGNED_SHORT: 5123,
  GL_FLOAT: 5126
};

const CONTROLS = {
  D_LEFT: 0,
  D_UP: 1,
  D_RIGHT: 2,
  D_DOWN: 3,
  A_BUTTON: 4,
  B_BUTTON: 5,

  KEY_IS_UP: 0,
  KEY_WAS_DOWN: 1,
  KEY_IS_DOWN: 2,
};

const INVENTORY = {
  INV_WEAPON: 0,
  INV_STAFF: 1,
  INV_HEAD: 2,
  INV_NECK: 3,
  INV_RING: 4,
};

const GAMESTATE = {
  GAMESTATE_EVENTS: 0,
  GAMESTATE_CURRENT_DUNGEON: 1,
  GAMESTATE_PLAYER: 2,

  PLAYER_XP: 0,
  PLAYER_LEVEL: 1,
  PLAYER_LEVEL_PENDING: 2,
  PLAYER_HP: 3,
  PLAYER_MAX_HP: 4,
  PLAYER_MP: 5,
  PLAYER_MAX_MP: 6,
  PLAYER_WEAPON_LEVEL: 7,
  PLAYER_DEFENSE: 8,
  PLAYER_DEBUFFS: 9,
  PLAYER_MAGIC_LEVELS: 10,
  PLAYER_SUMMON_LEVELS: 11,
  PLAYER_ACTIVE_SUMMONS: 12,
  PLAYER_GEM_UNLOCKED: 13,
  PLAYER_GEM_EQUIPED: 14,
  PLAYER_BONES: 15,
  PLAYER_FLESH: 16,
  PLAYER_SOULS: 17,

  MAGIC_FIRE: 0,
  MAGIC_ICE: 1,
  MAGIC_HOLY: 2,
  MAGIC_SHADOW: 3,
  MAGIC_NECROMANCY: 4,

  SUMMON_MAX_HP: 0,
  SUMMON_ATTACK: 1,
  SUMMON_DEFENSE: 2,

  SUMMON_TYPE: 0,
  SUMMON_HP: 1,
  SUMMON_DEBUFFS: 2,

  SUMMON_TYPE_SKELETON: 0,
  SUMMON_TYPE_ZOMBIE: 1,
  SUMMON_TYPE_SPIRIT: 2,

  DEBUFF_BURN: 0,
  DEBUFF_FREEZE: 1,
  DEBUFF_BLIND: 2,
  DEBUFF_ATTACK_DOWN: 3,
  DEBUFF_DEFENSE_DOWN: 4,
  DEBUFF_DEATH: 5,

  ENEMY_TYPE: 0,
  ENEMY_ELEMENT: 1,
  ENEMY_ALIVE: 2,
  ENEMY_MAX_HP: 3,
  ENEMY_HP: 4,
  ENEMY_ATTACK: 5,
  ENEMY_DEFENSE: 6,
  ENEMY_DEBUFFS: 7,
  ENEMY_INTENT: 8,

  ENEMY_INTENT_TYPE: 0,
  ENEMY_INTENT_VALUE: 1,

  ENEMY_INTENT_TYPE_NONE: 0,
  ENEMY_INTENT_TYPE_ATTACK: 1,
  ENEMY_INTENT_TYPE_BLOCK: 2,
  ENEMY_INTENT_TYPE_FIRE: 3,
  ENEMY_INTENT_TYPE_ICE: 4,
  ENEMY_INTENT_TYPE_HOLY: 5,
  ENEMY_INTENT_TYPE_SHADOW: 6,
};

let enemy_type = 0;
const ENEMY_TYPES = {
  ENEMY_TYPE_SKELETON: enemy_type++,
  ENEMY_TYPE_ZOMBIE: enemy_type++,
  ENEMY_TYPE_SPIRIT: enemy_type++,
  ENEMY_TYPE_BANDIT: enemy_type++,
  ENEMY_TYPE_MAGE: enemy_type++,
  ENEMY_TYPE_LICH: enemy_type++,
};

const PALETTES = {
  PALETTE_WALL: 1,
  PALETTE_PLAYER: 5,

  PALETTE_MAGE: 8,
  PALETTE_CLERIC: 11,
  PALETTE_BANDIT: 14,

  PALETTE_SKELETON: 26,
  PALETTE_ZOMBIE: 28,

  PALETTE_FIRE: 34,
  PALETTE_ICE: 36,
  PALETTE_HOLY: 38,
  PALETTE_SHADOW: 40,
};
module.exports.DEFINITIONS = { ...TEXTURE_TYPES, ...TEXTURES, ...INTERPOLATION_IDS, ...FONTS, ...GL, ...CONTROLS, ...INVENTORY, ...GAMESTATE, ...ENEMY_TYPES, ...PALETTES };